version: "3"
services:
  grafana:
    image: grafana/grafana:7.3.3-ubuntu
    container_name: akamai-grafana
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,grafana-worldmap-panel,grafana-googlesheets-datasource,grafana-polystat-panel
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - 3000:3000
    networks:
      - akamai-monitoring
    volumes:
      - akamai-grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  influxdb:
    image: influxdb
    container_name: akamai-influxdb
    restart: always
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    networks:
      - akamai-monitoring
    volumes:
      - akamai-influxdb-volume:/var/lib/influxdb
  telegraf:
    image: akatran/akamai-telegraf:latest
    container_name: akamai-telegraf
    restart: always
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - ACCOUNTSWITCHKEY=${ACCOUNTSWITCHKEY}
      - AKAMAI_ACCOUNT_ID=${AKAMAI_ACCOUNT_ID}
      - ENABLED_CPCODES=${ENABLED_CPCODES}
    networks:
      - akamai-monitoring
    volumes:
      - ~/.edgerc:/root/.edgerc
networks:
  akamai-monitoring:
volumes:
  akamai-grafana-volume:
    external: true
  akamai-influxdb-volume:
    external: true
