{
 "title": "Akamai - Overall Traffic and Volume - Historical",
 "tags": [ "Akamai" ],
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "accountid",
    "label": "AccountId",
    "query": "show TAG VALUES on telegraf FROM \"bytes-by-cpcode\" WITH KEY = \"accountid\""
   },
   {
    "name": "cpcode",
    "label": "CPCodes Filter",
    "query": "show TAG VALUES on telegraf FROM \"bytes-by-cpcode\" WITH KEY = \"cpcode\""
   }
  ]
 },
 "panels": [
  { "title": "Notes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Data on this Dashboard should be final data and will only appear in 1 to 2 days in a rears. Data for these panel come from the following OPEN APIs. Data on this Dashboard relies on the \"all\" cpcode.\n- enhancedtraffic-by-country - v1 - https://developer.akamai.com/api/core_features/reporting/enhancedtraffic-by-country.html\n- bytes-by-time - v1 - https://developer.akamai.com/api/core_features/reporting/bytes-by-time.html\n- hits-by-time - v1 - https://developer.akamai.com/api/core_features/reporting/hits-by-time.html\n- bytes-by-cpode - v1 - https://developer.akamai.com/api/core_features/reporting/bytes-by-cpcode.html\n- hits-by-cpcode - v1 - https://developer.akamai.com/api/core_features/reporting/hits-by-cpcode.html"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overall Traffic and Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "All Traffic ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps", "label": "Traffic" }
   ],
   "targets": [
    {
     "alias": "Edge Bits Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "edgeBitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "Midgress Bits Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "midgressBitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "Origin Bits Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "originBitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "Offload %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "bytesOffload" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Offload Minimum",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "bytesOffload" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Peak",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-time",
     "select": [
      [
       { "params": [ "edgeBitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "All Hits Traffic ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "alias": "Edge Hits Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-time",
     "select": [
      [
       { "params": [ "edgeHitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "Origin Hits Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-time",
     "select": [
      [
       { "params": [ "originHitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "Offload %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-time",
     "select": [
      [
       { "params": [ "hitsOffload" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits Offload Min",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hits-by-time",
     "select": [
      [
       { "params": [ "hitsOffload" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits Peak",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-time",
     "select": [
      [
       { "params": [ "edgeHitsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpcode", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Offload Total - by Date Selection",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "edge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "midgress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "midgressBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "origin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "originBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Hit Offload Total - by Date Selection",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "edge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-cpcode",
     "select": [
      [
       { "params": [ "edgeHits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "origin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-cpcode",
     "select": [
      [
       { "params": [ "originHits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Offload Total - Month Ago",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "edge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "midgress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "midgressBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "origin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes-by-cpcode",
     "select": [
      [
       { "params": [ "originBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Hit Offload Total - Month Ago",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "edge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-cpcode",
     "select": [
      [
       { "params": [ "edgeHits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    },
    {
     "alias": "origin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hits-by-cpcode",
     "select": [
      [
       { "params": [ "originHits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  { "title": "Country Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Volume by Country - Per Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enhancedtraffic-by-country",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits by Country - Per Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enhancedtraffic-by-country",
     "select": [
      [
       { "params": [ "edgeHits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "TB Volume by Country - Current Time Selection",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enhancedtraffic-by-country",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume by Country - by Date Selection",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enhancedtraffic-by-country",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume by Country - by Date Selection 1 Month Ago",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enhancedtraffic-by-country",
     "select": [
      [
       { "params": [ "edgeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpname", "operator": "=", "value": "allcpcodes" },
      { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Per Day - by CPCode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Edge Volume per Day - by CPCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_cpcode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpcode" ], "type": "tag" },
        { "params": [ "cpname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bytes-by-cpcode",
       "select": [
        [
         { "params": [ "edgeBytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "cpname", "operator": "=", "value": "allcpcodes" },
        { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
       ]
      }
     ]
    },
    {
     "title": "Midgress Volume per Day - by CPCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_cpcode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpcode" ], "type": "tag" },
        { "params": [ "cpname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bytes-by-cpcode",
       "select": [
        [
         { "params": [ "midgressBytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "cpname", "operator": "=", "value": "allcpcodes" },
        { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
       ]
      }
     ]
    },
    {
     "title": "Origin Volume per Day - by CPCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_cpcode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpcode" ], "type": "tag" },
        { "params": [ "cpname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bytes-by-cpcode",
       "select": [
        [
         { "params": [ "originBytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "cpname", "operator": "=", "value": "allcpcodes" },
        { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Hits Per Day - by CPCode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Edge Hits per Day - by CPCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Hits" }
     ],
     "targets": [
      {
       "alias": "$tag_cpcode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpcode" ], "type": "tag" },
        { "params": [ "cpname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hits-by-cpcode",
       "select": [
        [
         { "params": [ "edgeHits" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "cpname", "operator": "=", "value": "allcpcodes" },
        { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
       ]
      }
     ]
    },
    {
     "title": "Origin Hits per Day - by CPCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short", "label": "Hits" }
     ],
     "targets": [
      {
       "alias": "$tag_cpcode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpcode" ], "type": "tag" },
        { "params": [ "cpname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hits-by-cpcode",
       "select": [
        [
         { "params": [ "originHits" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "cpname", "operator": "=", "value": "allcpcodes" },
        { "condition": "AND", "key": "accountid", "operator": "=~", "value": "/^$accountid$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}